### ISSUE TITLE
Include license text in the PyPI tarball

### ISSUE THREAD

**Issue by mayorgatellez** [bitprophet/releases#37]
It's a mistake not to ship the LICENSE file in the released tarball--that makes it difficult or impossible for anyone to comply with their desired license terms.

I request this to you per Fedora Licensing Guidelines as I want to package this for the distribution.
See: https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text.

**Comment by bitprophet** [comment]
Kinda rude to open bug reports all "this is a mistake! how dare you not do this!" :P 

This line should (IIRC) have included the license in the sdist: https://github.com/bitprophet/releases/blob/9313de13d0df22c3857ec614a60f90a95801da0f/MANIFEST.in#L1

I just double checked and the local result of `python setup.py sdist` is definitely including the LICENSE:

```
» python setup.py sdist
running sdist
...
reading manifest template 'MANIFEST.in'
...
hard linking LICENSE -> releases-0.7.0
...
Creating tar archive
removing 'releases-0.7.0' (and everything under it)

» ls dist
releases-0.7.0.tar.gz

» tar tzvf dist/releases-0.7.0.tar.gz | grep LICENSE
-rw-r--r--  0 jforcier staff    1314 Jan  2 14:24 releases-0.7.0/LICENSE
```

Additionally, downloading the latest release from PyPI also appears to contain the LICENSE:

```
» pip install releases --download .                                
Collecting releases
  Downloading releases-0.7.0.tar.gz
  Saved ./releases-0.7.0.tar.gz
Successfully downloaded releases
» tar tzvf releases-0.7.0.tar.gz | grep LICENSE
-rw-r--r--  0 jforcier staff    1314 Dec 31  2013 releases-0.7.0/LICENSE
» tar xzf releases-0.7.0.tar.gz 
» head -n5 releases-0.7.0/LICENSE 
Copyright (c) 2014, Jeff Forcier
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
```

----

If some older release is missing the LICENSE or if you can find another public copy that I was responsible for uploading, missing it, please let me know!
