### ISSUE TITLE
Add support for including fixes in round releases

### ISSUE THREAD

**Issue by vmalloc** [bitprophet/releases#39]
Currently if a bug is included in a changelog, it will always be "floating" waiting for the next bugfix release, even if the meaning is that it is included in the major release...

It would be nice to add a configuration option to force `releases` to include bugfixes in their intended place...

**Comment by keimlink** [comment]
Have you tried using the `major` keyword?

**Comment by bitprophet** [comment]
@vmalloc can you clarify your exact situation (e.g. with a copy of your changelog file & exactly how you expected it to render)? Want to make sure there's no confusion re: major vs minor vs bugfix releases.

By default, bugs go out in bugfix releases, e.g. 1.2.3. As @keimlink says, you can force a bug to be included in **minor** releases (e.g. 1.2.0 or 2.7.0) by marking them `major` (see the docs for details on how that's formatted).

If you truly meant **major**, as in, 2.0, that's not as well-tested yet, so I'm not sure exactly what would happen. My guess is it'd behave similar to a minor release.

**Comment by vmalloc** [comment]
But of course - `major` is what I was looking for... Thanks and sorry for wasting your time :-)
