### ISSUE TITLE
Order/sort changelog entries within each release bucket

### ISSUE THREAD

**Issue by bitprophet** [bitprophet/releases#42]
For nontrivial releases w/ lots of line items, it looks pretty messy to have an effectively unordered list with bug/feature/support all mixed up. Not to mention it's harder to read when you know a given fix is in a given release & are trying to scan for it.

Technically they're sorted temporally (IIRC) but that doesn't usually matter to anybody.

Would like to reorder things per-bucket so they're displayed in feature-bug-support order. Ideally configurable but that's probably a phase 2 kind of thing.

Another phase 2 kind of thing would be to flag specific line items as "major" or "emphasis" and visually highlight them...but that probably belongs in another ticket.

**Comment by keimlink** [comment]
Great idea! :thumbsup:
