### ISSUE TITLE
Tag 1.3.1 in git

### ISSUE THREAD

**Issue by jeremycline** [bitprophet/releases#69]
Hi, I noticed that PyPI has version 1.3.1, but the latest git tag is 1.3.0. Would it be possible to tag 1.3.1?

Thanks!

**Comment by bitprophet** [comment]
Seems I never did a `git push --tags` last time, it was there locally but not remotely. Pushed! Thanks & sorry :)

**Comment by jeremycline** [comment]
Happens to me all the time 😄 

Thanks so much!
