### ISSUE TITLE
releases 1.3.1 sphinx version constraint too tough for pipenv, release new pypi version?

### ISSUE THREAD

**Issue by tony** [bitprophet/releases#71]
https://github.com/bitprophet/releases/compare/1.3.1...master

f5fcad3 didn't make it in

```
tmuxp-qUA_BCEU ❯ pipenv graph
aafigure==0.6
alagitpull==0.0.13
  - alabaster [required: ==0.7.10, installed: 0.7.10]
pytest-rerunfailures==3.1
  - pytest [required: >=2.7.3, installed: 3.2.3]
    - py [required: >=1.4.33, installed: 1.4.34]
    - setuptools [required: Any, installed: 36.6.0]
releases==1.3.1
  - semantic-version [required: <3.0, installed: 2.6.0]
  - sphinx [required: <1.5,>=1.3, installed: 1.6.4]
    - alabaster [required: >=0.7,<0.8, installed: 0.7.10]
    - babel [required: !=2.0,>=1.3, installed: 2.5.1]
      - pytz [required: >=0a, installed: 2017.2]
    - docutils [required: >=0.11, installed: 0.14]
    - imagesize [required: Any, installed: 0.7.1]
    - Jinja2 [required: >=2.3, installed: 2.9.6]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - Pygments [required: >=2.0, installed: 2.2.0]
    - requests [required: >=2.0.0, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
      - chardet [required: <3.1.0,>=3.0.2, installed: 3.0.4]
      - idna [required: >=2.5,<2.7, installed: 2.6]
      - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
    - setuptools [required: Any, installed: 36.6.0]
    - six [required: >=1.5, installed: 1.11.0]
    - snowballstemmer [required: >=1.1, installed: 1.2.1]
    - sphinxcontrib-websupport [required: Any, installed: 1.0.1]
tmuxp==1.3.4
  - click [required: ==6.7, installed: 6.7]
  - colorama [required: ==0.3.9, installed: 0.3.9]
  - kaptan [required: >=0.5.7, installed: 0.5.8]
    - PyYAML [required: Any, installed: 3.12]
  - libtmux [required: ==0.7.5, installed: 0.7.5]
```

**Comment by tony** [comment]
Workaround is to use ``--skip-lock`` for now

**Comment by bitprophet** [comment]
Oh huh totally forgot about that, was not intending to just sit on it :sad: Will cut 1.3.2. Thanks for the report!

**Comment by bitprophet** [comment]
1.3.2 should be on PyPI now, despite some irritating mishaps. Please follow up if that doesn't install better under your setup.

**Comment by bitprophet** [comment]
Hrm yup today's just not a good day, Sphinx 1.6 seems to be breaking us pretty badly. Look out for a 1.3.3...

**Comment by bitprophet** [comment]
Suspect the real issue is the pin itself was wrong, there is no sphinx 2.x as far as I can tell, but it's either 1.5 or 1.6 that started breaking their internal APIs which in turn broke us. I may need to rephrase it as `sphinx>=1.3,<1.6`? Checking.

**Comment by bitprophet** [comment]
Yea 1.6 changed arity of `app.config.init_values`. Put in a workaround; now my test suite passes, though we still get a grazillion ANSI-red warnings, which I will try to fix next lest I get bombarded with issues for that 😆

**Comment by bitprophet** [comment]
Those warnings seem to have been in since 1.4, so I bet this is actually related to the arity thing, since...the arg that came and then went, was a warnings runner! which we were handing a dummy/noop lambda into - thus muting those warnings.

Gonna see if there's a better way, such as configuring the app at runtime, since there ought to be specific config options for these specific warnings (going by their issues...)

**Comment by bitprophet** [comment]
Grump, got the unit test suite's view of things squared away, only to find some more Sphinx API changes when I ran the integration suite. Still digging. Also adding a full test matrix to Travis so this sort of thing doesn't cause regressions.

**Comment by bitprophet** [comment]
Cool. I think that has all been ironed out, and the matrix is happy, meaning hopefully we didn't torch any existing setups. Took the time to drop 2.6/3.3 support (those cells were dying thanks to Sphinx anyway) and it will be out as Releases 1.4.0 momentarily.
