### ISSUE TITLE
six dependency removal

### ISSUE THREAD

**Issue by pgajdos** [bitprophet/releases#99]
Python 2 is not supported anymore, so `six` dependency should not be needed.

**Comment by pgajdos** [comment]
`six` is used on few places, I guess something around
https://build.opensuse.org/package/view_file/home:pgajdos:python/python-releases/python-releases-no-six.patch

**Comment by bitprophet** [comment]
This should be fixed as of the latest major release!

**Comment by pgajdos** [comment]
Thank you
